#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"
#require "#{File.dirname __FILE__}/../config/environment"


username = ''                       
### OR ###
username = 'kafleumesh@gmail.com'

puts "Using username='#{username}'..." 
Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: username, 
  password: 'Tahachaina1'
}
Mailman::Application.run do
  default do
    begin
      p "Found a new message"
      if message.multipart?
        the_message_html = message.html_part.body.decoded
        the_message_text = message.text_part.body.decoded
        the_message_attachments = []
        message.attachments.each do |attachment|
          #binding.pry
          #file = StringIO.new(Base64.decode64(string))
          #puts file.respond_to?(:original_filename)
          #puts file.respond_to?(:content_type)
          #binding.pry
          attachment = Attachment.new
          attachment.attached_file = file
          attachment.save
          the_message_attachments << attachment
        end
      else
        the_message_html = message.body.decoded
        the_message_text = message.body.decoded
        the_message_attachments = []
      end
      Curriculumvitae.create(:from => message.from.first, :to => message.to.first, :subject => message.subject, :html_body => the_message_html, :text_body => the_message_text, :attachment => message.attachment)
    end
  end
end